'use client';

import { useState } from 'react';
import { ArrowBack, ArrowForward, Check, EditOutlined, Refresh, TipsAndUpdates } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardActionArea, CardContent, MenuItem, Stack, Step, StepButton, Stepper, TextField, Typography, useMediaQuery, useTheme } from '@mui/material';
import { Design, contentTypes, formats, Format, objectives, suggestCopy, tones } from '@/lib/studio';
import { Choices, Field, Panel, Photos } from './Fields';

export const steps = ['Intención', 'Producto', 'Mensaje', 'Estilo', 'Revisión'];
const titles = ['¿Qué vas a crear hoy?', 'Muéstranos tu producto.', 'Encuentra las palabras.', 'Dale tu propio estilo.', 'Todo listo para diseñar.'];
const descriptions = ['Elige lo que quieres contar. Te acompañamos paso a paso.', 'Agrega entre una y tres fotos. La primera será la imagen principal.', 'Ajusta el mensaje que tus clientes leerán.', 'Elige un formato y una apariencia para tu publicación.', 'Revisa los datos. Después podrás ajustar cada detalle en el editor.'];

export function CreateFlow({ design: d, update, step, setStep, onCreate }: { design: Design; update: (patch: Partial<Design>) => void; step: number; setStep: (step: number) => void; onCreate: () => void }) {
  const [variant, setVariant] = useState(0);
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'), { noSsr: true });
  const valid = step === 1 ? Boolean(d.product.trim() && d.images.length) : step === 2 ? Boolean(d.title.trim() && d.cta.trim()) : true;
  const next = () => { if (!valid) return; if (step === 1 && !d.title) update(suggestCopy(d)); setStep(step + 1); };
  return <Box className="flow" sx={{ pb: 2 }}>
    <Stack spacing={1} sx={{ mb: 3 }}><Typography variant="overline" color="primary.dark" sx={{ fontWeight: 800, letterSpacing: '.12em' }}>NUEVA PUBLICACIÓN</Typography><Typography variant="h1">{titles[step]}</Typography><Typography color="text.secondary" sx={{ maxWidth: 680 }}>{descriptions[step]}</Typography></Stack>
    <Stepper activeStep={step} orientation={isMobile ? 'vertical' : 'horizontal'} alternativeLabel={!isMobile} sx={{ mb: 3, '& .MuiStepLabel-label': { fontSize: { xs: '.78rem', sm: '.8rem' } }, '& .MuiStepIcon-root.Mui-active, & .MuiStepIcon-root.Mui-completed': { color: 'primary.main' } }}>{steps.map((name, index) => <Step key={name} completed={index < step}><StepButton color="inherit" onClick={() => index <= step && setStep(index)}>{name}</StepButton></Step>)}</Stepper>
    {step === 1 && <Alert severity="info" icon={<TipsAndUpdates />}>Para continuar, escribe el nombre de tu producto o servicio y añade al menos una foto.</Alert>}
    {step === 2 && <Alert severity="info" sx={{ mb: 2 }}>Completa el título y el llamado a la acción para poder continuar.</Alert>}
    <Box sx={{ mt: 2 }}>
      {step === 0 && <Panel><Stack spacing={2.5}><Choices label="Tipo de contenido" options={contentTypes} value={d.type} onChange={type => update({ type, ...(type === 'Historia' ? { format: 'story' as Format } : {}), ...(type === 'Oferta' ? { objective: 'Promocionar una oferta' } : type === 'Invitación' ? { objective: 'Invitar a un evento' } : {}) })} /><Choices label="¿Qué quieres conseguir?" options={objectives} value={d.objective} onChange={objective => update({ objective })} /><Alert severity="success">Una publicación con un objetivo claro es más fácil de entender. Puedes crear otras versiones después.</Alert></Stack></Panel>}
      {step === 1 && <ResponsiveGrid><Panel title="El protagonista"><Stack spacing={2}><Field label="Producto o servicio" value={d.product} onChange={product => update({ product })} required maxLength={80} placeholder="Ej. Taza de cerámica hecha a mano" /><Field label="Descripción" multiline value={d.description} onChange={description => update({ description })} maxLength={350} placeholder="¿Qué lo hace especial? Materiales, beneficios, sabores…" /><Photos images={d.images} onChange={images => update({ images, selectedImage: 0 })} /></Stack></Panel><Panel title="Los detalles que importan"><Stack spacing={2}><Field label="Precio o promoción · opcional" value={d.price} onChange={price => update({ price })} maxLength={45} placeholder="Ej. S/ 35 o 2 por S/ 60" /><Field label="Fecha o vigencia · opcional" value={d.validity} onChange={validity => update({ validity })} maxLength={60} placeholder="Ej. Válido hasta el 30 de octubre" /><Field label="Contacto para esta publicación" type="tel" value={d.contact} onChange={contact => update({ contact })} maxLength={35} placeholder="WhatsApp o teléfono" /><Alert severity="info">El contacto viene de tu negocio. Puedes cambiarlo solo para esta publicación.</Alert></Stack></Panel></ResponsiveGrid>}
      {step === 2 && <ResponsiveGrid><Panel title="Tu mensaje"><Stack spacing={2}><Field label="Título" value={d.title} onChange={title => update({ title })} maxLength={80} required /><Field label="Texto del diseño" multiline value={d.body} onChange={body => update({ body })} maxLength={180} /><Field label="Llamado a la acción" value={d.cta} onChange={cta => update({ cta })} maxLength={40} required /><Field label="Hashtags" value={d.hashtags} onChange={hashtags => update({ hashtags })} maxLength={250} /></Stack></Panel><Panel title="Un poco de inspiración"><Stack spacing={2}><Choices label="Tono de comunicación" options={tones} value={d.tone} onChange={tone => update({ tone })} /><Typography variant="body2" color="text.secondary">Sugerencias basadas en plantillas y tus datos. La ayuda con IA estará disponible al conectar el generador.</Typography><Button variant="outlined" startIcon={<Refresh />} onClick={() => { update(suggestCopy(d, variant + 1)); setVariant(variant + 1); }}>Sugerir otra opción</Button><Field label="Texto para acompañar la publicación" multiline value={d.caption} onChange={caption => update({ caption })} maxLength={1500} /><Typography variant="caption" color="text.secondary">Este texto y los hashtags se copian por separado; no se imprimen sobre la imagen.</Typography></Stack></Panel></ResponsiveGrid>}
      {step === 3 && <ResponsiveGrid><Panel title="Apariencia"><Stack spacing={2.5}><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' }, gap: 1.25 }}>{['Moderno', 'Vibrante', 'Minimalista'].map(style => <Card key={style} variant="outlined" sx={{ borderColor: d.style === style ? 'primary.main' : 'divider', bgcolor: d.style === style ? '#EEF2FF' : 'background.paper' }}><CardActionArea onClick={() => update({ style, font: style === 'Minimalista' ? 'serif' : 'sans', color: style === 'Vibrante' ? '#FF375F' : d.brand.primary, background: style === 'Minimalista' ? '#F7F9FC' : d.brand.secondary })}><Box sx={{ height: 110, m: 1.25, borderRadius: 2, position: 'relative', overflow: 'hidden', bgcolor: style === 'Vibrante' ? '#FF375F' : style === 'Minimalista' ? '#F7F9FC' : '#7188F3' }}><Typography sx={{ position: 'absolute', left: 12, bottom: 12, color: style === 'Vibrante' || style === 'Minimalista' ? 'text.primary' : 'common.white', fontWeight: 800 }}>{style}</Typography></Box><CardContent sx={{ pt: 0, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><Typography fontWeight={700}>{style}</Typography>{d.style === style && <Check color="primary" fontSize="small" />}</CardContent></CardActionArea></Card>)}</Box><Choices label="Tono" options={tones} value={d.tone} onChange={tone => update({ tone })} /></Stack></Panel><Panel title="Formato y preferencias"><Stack spacing={2}><TextField select fullWidth label="Formato de salida" value={d.format} onChange={event => update({ format: event.target.value as Format })}>{Object.entries(formats).map(([key, format]) => <MenuItem value={key} key={key}>{format.label} · {format.width} × {format.height}</MenuItem>)}</TextField><Field label="Instrucciones para el generador · opcional" multiline value={d.instructions} onChange={instructions => update({ instructions })} maxLength={700} placeholder="Ej. Conserva el color del producto y usa un fondo cálido." /><Typography variant="caption" color="text.secondary">Guardaremos tus indicaciones. La maqueta local no interpreta instrucciones con IA.</Typography></Stack></Panel></ResponsiveGrid>}
      {step === 4 && <Panel title="Resumen de tu publicación"><Stack spacing={1.25}><Box sx={{ display: 'flex', gap: 1, overflowX: 'auto', pb: 1 }}>{d.images.map((src, index) => <Box component="img" key={index} src={src} alt={`Referencia ${index + 1}`} sx={{ width: 84, height: 64, objectFit: 'cover', borderRadius: 2, flexShrink: 0 }} />)}</Box>{[{ label: 'Contenido y objetivo', value: `${d.type} · ${d.objective}`, step: 0 }, { label: 'Producto', value: [d.product, d.description, d.price, d.validity, d.contact].filter(Boolean).join(' · '), step: 1 }, { label: 'Mensaje', value: [d.title, d.body, d.cta].filter(Boolean).join(' · '), step: 2 }, { label: 'Estilo y formato', value: `${d.style} · ${d.tone} · ${formats[d.format].label}`, step: 3 }, { label: 'Preferencias', value: d.instructions || 'Sin indicaciones adicionales', step: 3 }].map(row => <Box key={row.label} sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, py: 1.5, borderBottom: '1px solid', borderColor: 'divider' }}><Box><Typography variant="caption" color="text.secondary">{row.label}</Typography><Typography variant="body2" fontWeight={600}>{row.value}</Typography></Box><Button size="small" variant="text" startIcon={<EditOutlined />} onClick={() => setStep(row.step)}>Editar</Button></Box>)}<Alert severity="info">Crearás una maqueta editable con tus fotos y datos. La generación con IA se conectará en la siguiente etapa.</Alert></Stack></Panel>}
    </Box>
    <Stack direction={{ xs: 'column-reverse', sm: 'row' }} spacing={1.5} alignItems={{ xs: 'stretch', sm: 'center' }} sx={{ mt: 2.5 }}><Button variant="outlined" startIcon={<ArrowBack />} onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}>Atrás</Button><Typography variant="caption" color="text.secondary" sx={{ flex: 1, textAlign: { xs: 'center', sm: 'left' } }}>Paso {step + 1} de 5</Typography>{step < 4 ? <Button variant="contained" endIcon={<ArrowForward />} onClick={next} disabled={!valid}>Continuar</Button> : <Button variant="contained" endIcon={<ArrowForward />} onClick={onCreate} disabled={!d.product.trim() || !d.images.length || !d.title.trim() || !d.cta.trim()}>Crear maqueta</Button>}</Stack>
  </Box>;
}

function ResponsiveGrid({ children }: { children: React.ReactNode }) {
  return <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' }, gap: 2 }}>{children}</Box>;
}
