'use client';
import { Design, contentTypes, formats, Format, objectives, tones, suggestCopy } from '@/lib/studio';
import { Choices, Field, Panel, Photos } from './Fields';
import { ArrowLeft, ArrowRight, Check, Pencil, Sparkles } from 'lucide-react';
import { useState } from 'react';

export const steps = ['Intención', 'Producto', 'Mensaje', 'Estilo', 'Revisión'];
export function CreateFlow({ design: d, update, step, setStep, onCreate }: { design: Design; update: (patch: Partial<Design>) => void; step: number; setStep: (step: number) => void; onCreate: () => void }) {
  const [variant, setVariant] = useState(0);
  const valid = step === 1 ? Boolean(d.product.trim() && d.images.length) : step === 2 ? Boolean(d.title.trim() && d.cta.trim()) : true;
  const next = () => { if (!valid) return; if (step === 1 && !d.title) update(suggestCopy(d)); setStep(step + 1); };
  return <div className="flow"><div className="page-heading"><span className="eyebrow">UNA IDEA, UNA PUBLICACIÓN</span><h1>{['¿Qué vas a crear hoy?', 'Muéstranos tu producto.', 'Encuentra las palabras.', 'Dale tu propio estilo.', 'Todo listo para diseñar.'][step]}</h1><p>{['Elige lo que quieres contar. Te acompañamos paso a paso.', 'Agrega entre una y tres fotos. La primera será la imagen principal.', 'Ajusta el mensaje que tus clientes leerán.', 'Elige un formato y una apariencia para tu publicación.', 'Revisa los datos. Después podrás ajustar cada detalle en el editor.'][step]}</p></div>
    <ol className="stepper">{steps.map((name, i) => <li key={name} className={i === step ? 'active' : i < step ? 'done' : ''}><button type="button" disabled={i > step} onClick={() => setStep(i)} aria-current={i === step ? 'step' : undefined}><span>{i < step ? <Check size={14} /> : i + 1}</span><b>{name}</b></button></li>)}</ol>
    {step === 0 && <Panel><Choices label="Tipo de contenido" options={contentTypes} value={d.type} onChange={type => update({ type, ...(type === 'Historia' ? { format: 'story' as Format } : {}), ...(type === 'Oferta' ? { objective: 'Promocionar una oferta' } : type === 'Invitación' ? { objective: 'Invitar a un evento' } : {}) })} /><Choices label="¿Qué quieres conseguir?" options={objectives} value={d.objective} onChange={objective => update({ objective })} /><div className="tip">Una publicación con un objetivo claro es más fácil de entender. Puedes crear otras versiones después.</div></Panel>}
    {step === 1 && <div className="two-columns"><Panel title="El protagonista"><Field label="Producto o servicio" value={d.product} onChange={product => update({ product })} required maxLength={80} placeholder="Ej. Taza de cerámica hecha a mano" /><Field label="Descripción" multiline value={d.description} onChange={description => update({ description })} maxLength={350} placeholder="¿Qué lo hace especial? Materiales, beneficios, sabores…" /><Photos images={d.images} onChange={images => update({ images, selectedImage: 0 })} /></Panel><Panel title="Los detalles que importan"><Field label="Precio o promoción · opcional" value={d.price} onChange={price => update({ price })} maxLength={45} placeholder="Ej. S/ 35 o 2 por S/ 60" /><Field label="Fecha o vigencia · opcional" value={d.validity} onChange={validity => update({ validity })} maxLength={60} placeholder="Ej. Válido hasta el 30 de octubre" /><Field label="Contacto para esta publicación" type="tel" value={d.contact} onChange={contact => update({ contact })} maxLength={35} placeholder="WhatsApp o teléfono" /><div className="tip">El contacto viene de tu negocio. Puedes cambiarlo solo para esta publicación.</div></Panel></div>}
    {step === 2 && <div className="two-columns"><Panel title="Tu mensaje"><Field label="Título" value={d.title} onChange={title => update({ title })} maxLength={80} required /><Field label="Texto del diseño" multiline value={d.body} onChange={body => update({ body })} maxLength={180} /><Field label="Llamado a la acción" value={d.cta} onChange={cta => update({ cta })} maxLength={40} required /><Field label="Hashtags" value={d.hashtags} onChange={hashtags => update({ hashtags })} maxLength={250} /></Panel><Panel title="Un poco de inspiración"><Choices label="Tono de comunicación" options={tones} value={d.tone} onChange={tone => update({ tone })} /><p className="hint">Sugerencias basadas en plantillas y tus datos. La ayuda con IA estará disponible al conectar el generador.</p><button type="button" className="secondary" onClick={() => { update(suggestCopy(d, variant + 1)); setVariant(variant + 1); }}><Sparkles size={18} />Sugerir otra opción</button><Field label="Texto para acompañar la publicación" multiline value={d.caption} onChange={caption => update({ caption })} maxLength={1500} /><p className="hint">Este texto y los hashtags se copian por separado; no se imprimen sobre la imagen.</p></Panel></div>}
    {step === 3 && <div className="two-columns"><Panel title="Apariencia"><div className="style-options">{['Moderno', 'Vibrante', 'Minimalista'].map(style => <button type="button" aria-pressed={d.style === style} className={`style-card ${d.style === style ? 'selected' : ''}`} key={style} onClick={() => update({ style, font: style === 'Minimalista' ? 'serif' : 'sans', color: style === 'Vibrante' ? '#bb472c' : d.brand.primary, background: style === 'Minimalista' ? '#faf9f6' : d.brand.secondary })}><div className={`style-sample style-${style.toLowerCase()}`}><span>Tu marca</span><b>Algo<br />especial.</b><i /></div><strong>{style}</strong>{d.style === style && <Check size={16} />}</button>)}</div><Choices label="Tono" options={tones} value={d.tone} onChange={tone => update({ tone })} /></Panel><Panel title="Formato y preferencias"><label className="field"><span>Formato de salida</span><select value={d.format} onChange={e => update({ format: e.target.value as Format })}>{Object.entries(formats).map(([key, f]) => <option value={key} key={key}>{f.label} · {f.width} × {f.height}</option>)}</select></label><Field label="Instrucciones para el generador · opcional" multiline value={d.instructions} onChange={instructions => update({ instructions })} maxLength={700} placeholder="Ej. Conserva el color del producto y usa un fondo cálido." /><p className="hint">Guardaremos tus indicaciones. La maqueta local no interpreta instrucciones con IA.</p></Panel></div>}
    {step === 4 && <Panel title="Resumen de tu publicación"><div className="review-photos">{d.images.map((src, i) => <img key={i} src={src} alt={`Referencia ${i + 1}`} />)}</div>{[{ label: 'Contenido y objetivo', value: `${d.type} · ${d.objective}`, step: 0 }, { label: 'Producto', value: [d.product, d.description, d.price, d.validity, d.contact].filter(Boolean).join(' · '), step: 1 }, { label: 'Mensaje', value: [d.title, d.body, d.cta].filter(Boolean).join(' · '), step: 2 }, { label: 'Estilo y formato', value: `${d.style} · ${d.tone} · ${formats[d.format].label}`, step: 3 }, { label: 'Preferencias', value: d.instructions || 'Sin indicaciones adicionales', step: 3 }].map(row => <div className="review-row" key={row.label}><div><small>{row.label}</small><p>{row.value}</p></div><button type="button" className="icon-button" aria-label={`Editar ${row.label}`} onClick={() => setStep(row.step)}><Pencil size={17} /></button></div>)}<div className="tip">Crearás una maqueta editable con tus fotos y datos. La generación con IA se conectará en la siguiente etapa.</div></Panel>}
    <div className="flow-actions"><button type="button" className="secondary" onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0}><ArrowLeft size={18} />Atrás</button><span className="hint">Paso {step + 1} de 5</span>{step < 4 ? <button type="button" className="primary" onClick={next} disabled={!valid}>Continuar<ArrowRight size={18} /></button> : <button type="button" className="primary" onClick={onCreate} disabled={!d.product.trim() || !d.images.length || !d.title.trim() || !d.cta.trim()}><Sparkles size={18} />Crear maqueta</button>}</div>
  </div>;
}
