'use client';
import { useEffect, useRef, useState } from 'react';
import { Copy, Download, Save, Send, Share2, Undo2 } from 'lucide-react';
import { Design, formats, Format } from '@/lib/studio';
import { downloadBlob, pngBlob, renderDesign } from '@/lib/studio-renderer';
import { Choices, Field, Panel, Photos } from './Fields';

export function Editor({ design: d, update, onSave, notify, onBack }: { design: Design; update: (patch: Partial<Design>) => void; onSave: () => Promise<void>; notify: (message: string, error?: boolean) => void; onBack: () => void }) {
  const [preview, setPreview] = useState<{ url: string; blob: Blob; design: Design } | null>(null);
  const [renderError, setRenderError] = useState(''), [rendering, setRendering] = useState(true), [retry, setRetry] = useState(0);
  const [tab, setTab] = useState('Texto'), [element, setElement] = useState('Texto'), [request, setRequest] = useState('');
  const [date, setDate] = useState(d.schedule?.at || ''), [channel, setChannel] = useState(d.schedule?.channel || 'Instagram');
  const [saving, setSaving] = useState(false);
  const drag = useRef<{ x: number; y: number; a: number; b: number; width: number; height: number; element: string } | null>(null);
  useEffect(() => {
    let live = true, url = '';
    setRendering(true); setRenderError('');
    const timer = setTimeout(() => {
      void renderDesign(d).then(pngBlob).then(blob => {
        if (!live) return;
        url = URL.createObjectURL(blob); setPreview({ url, blob, design: d }); setRendering(false);
      }).catch(e => { if (live) { setRenderError((e as Error).message); setRendering(false); } });
    }, 100);
    return () => { live = false; clearTimeout(timer); if (url) URL.revokeObjectURL(url); };
  }, [d, retry]);
  const ready = !!preview && preview.design === d && !rendering && !renderError;
  const filename = `${d.product.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '-').slice(0, 50) || 'publicacion'}-${d.format}.png`;
  async function share() {
    if (!ready || !preview) return;
    const file = new File([preview.blob], filename, { type: 'image/png' });
    try {
      if (navigator.canShare?.({ files: [file] }) && navigator.share) await navigator.share({ files: [file], title: d.title, text: d.caption });
      else { downloadBlob(preview.blob, filename); notify('Tu navegador no permite compartir archivos directamente. Iniciamos la descarga para que puedas adjuntarla en tu red social.'); }
    } catch (error) { if ((error as Error).name !== 'AbortError') notify('No se pudo compartir. Puedes descargar la imagen y enviarla manualmente.', true); }
  }
  async function copy() {
    try { await navigator.clipboard.writeText(d.caption || `${d.title}\n${d.body}\n${d.cta}\n${d.hashtags}`); notify('Texto copiado. Ya puedes pegarlo en tu publicación.'); }
    catch { notify('No se pudo copiar. Selecciona el texto del campo y cópialo manualmente.', true); }
  }
  const move = (a: number, b: number, target: string) => update(target === 'Texto' ? { textX: Math.max(4, Math.min(18, a)), textY: Math.max(45, Math.min(70, b)) } : { imageX: Math.max(0, Math.min(100 - d.imageWidth, a)), imageY: Math.max(12, Math.min(55, b)) });
  const range = (label: string, key: 'textX' | 'textY' | 'textSize' | 'imageX' | 'imageY' | 'imageWidth', min: number, max: number) => <label className="range-field"><span>{label}<b>{Math.round(d[key])}</b></span><input type="range" min={min} max={max} value={d[key]} onChange={e => { const v = Number(e.target.value); update({ [key]: v, ...(key === 'imageWidth' ? { imageX: Math.min(d.imageX, 100 - v) } : {}) }); }} /></label>;
  return <div className="editor"><div className="page-heading editor-heading"><div><span className="eyebrow">TU ESTUDIO CREATIVO</span><h1>Hazlo tuyo.</h1><p>Edita tu maqueta y llévala a tus redes.</p></div><button className="secondary" onClick={onBack}><Undo2 size={17} />Volver al resumen</button></div>
    <div className="editor-grid"><section className="preview-panel" aria-label="Vista previa del diseño"><div className="preview-toolbar"><label className="field"><span>Formato de salida</span><select value={d.format} onChange={e => update({ format: e.target.value as Format })}>{Object.entries(formats).map(([id, f]) => <option value={id} key={id}>{f.label}</option>)}</select></label><span className="tag">Maqueta local</span></div>
      <div className="preview-stage"><div className="canvas-wrap" style={{ aspectRatio: `${formats[d.format].width}/${formats[d.format].height}`, maxWidth: d.format === 'story' || d.format === 'whatsapp' ? 295 : 520 }}>
        {preview && <img src={preview.url} className="flyer-preview" alt={`Vista previa: ${d.title}`} draggable={false} />}
        {tab === 'Posición' && <div className="move-surface" role="group" tabIndex={0} aria-label={`Mover ${element.toLowerCase()}. Arrastra o usa las flechas.`} onKeyDown={e => { const keys: Record<string, number[]> = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }; if (keys[e.key]) { e.preventDefault(); const [a, b] = keys[e.key]; move((element === 'Texto' ? d.textX : d.imageX) + a, (element === 'Texto' ? d.textY : d.imageY) + b, element); } }} onPointerDown={e => { const rect = e.currentTarget.getBoundingClientRect(); drag.current = { x: e.clientX, y: e.clientY, a: element === 'Texto' ? d.textX : d.imageX, b: element === 'Texto' ? d.textY : d.imageY, width: rect.width, height: rect.height, element }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { const p = drag.current; if (p) move(p.a + (e.clientX - p.x) / p.width * 100, p.b + (e.clientY - p.y) / p.height * 100, p.element); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><div className="selection-outline" style={element === 'Texto' ? { left: `${d.textX}%`, top: `${d.textY}%`, width: `${94 - d.textX}%`, height: `${93 - d.textY}%` } : { left: `${d.imageX}%`, top: `${d.imageY}%`, width: `${d.imageWidth}%`, height: '40%' }}><span>{element}</span></div></div>}
        {!preview && !renderError && <div className="render-placeholder">Preparando tu diseño…</div>}
      </div></div><div className="preview-meta"><span>{formats[d.format].width} × {formats[d.format].height} px · PNG</span><span aria-live="polite">{rendering ? 'Actualizando…' : renderError ? 'Error de vista previa' : 'Vista previa actualizada'}</span></div>{renderError && <div className="error" role="alert">{renderError}<button className="secondary" onClick={() => setRetry(r => r + 1)}>Reintentar</button></div>}
      <p className="hint">La imagen descargada es exactamente esta vista previa. Cada formato adapta el espacio disponible.</p>
    </section>
    <Panel className="editor-controls"><div className="editor-tabs" aria-label="Herramientas del editor">{['Texto', 'Imagen', 'Estilo', 'Posición'].map(t => <button aria-pressed={tab === t} key={t} onClick={() => setTab(t)} className={tab === t ? 'active' : ''}>{t}</button>)}</div>
      {tab === 'Texto' && <><Field label="Título" value={d.title} onChange={title => update({ title })} maxLength={80} /><Field label="Descripción del flyer" multiline value={d.body} onChange={body => update({ body })} maxLength={180} /><Field label="Llamado a la acción" value={d.cta} onChange={cta => update({ cta })} maxLength={40} /><div className="two-fields"><Field label="Precio o promoción" value={d.price} onChange={price => update({ price })} maxLength={45} /><Field label="Fecha o vigencia" value={d.validity} onChange={validity => update({ validity })} maxLength={60} /></div><Field label="Contacto" value={d.contact} onChange={contact => update({ contact })} maxLength={35} /></>}
      {tab === 'Imagen' && <><Choices label="Ajuste de la foto" options={['Foto completa', 'Llenar marco']} value={d.imageFit === 'cover' ? 'Llenar marco' : 'Foto completa'} onChange={value => update({ imageFit: value === 'Llenar marco' ? 'cover' : 'contain' })} /><p className="hint">Elige la foto principal. Las otras fotos quedan guardadas como referencias para el generador.</p><div className="image-picker">{d.images.map((src, i) => <button key={i} className={i === d.selectedImage ? 'selected' : ''} aria-label={`Usar foto ${i + 1}`} aria-pressed={i === d.selectedImage} onClick={() => update({ selectedImage: i })}><img src={src} alt={`Foto ${i + 1}`} /></button>)}</div><Photos images={d.images} onChange={images => update({ images, selectedImage: 0 })} />{!d.images.length && <p className="error">Agrega una foto para guardar o descargar.</p>}</>}
      {tab === 'Estilo' && <><Choices label="Estilo visual" options={['Moderno', 'Vibrante', 'Minimalista']} value={d.style} onChange={style => update({ style })} /><Choices label="Tipografía" options={['Sans', 'Serif']} value={d.font === 'sans' ? 'Sans' : 'Serif'} onChange={value => update({ font: value === 'Sans' ? 'sans' : 'serif' })} /><div className="color-row"><label>Color principal<input aria-label="Color principal del flyer" type="color" value={d.color} onChange={e => update({ color: e.target.value })} /></label><label>Fondo<input aria-label="Fondo del flyer" type="color" value={d.background} onChange={e => update({ background: e.target.value })} /></label></div><button className="secondary" onClick={() => update({ color: d.brand.primary, background: d.brand.secondary })}>Usar colores de mi marca</button></>}
      {tab === 'Posición' && <><Choices label="Elemento a mover" options={['Texto', 'Imagen']} value={element} onChange={setElement} /><p className="hint">Arrastra sobre la vista previa, usa las flechas del teclado o ajusta estos controles.</p>{element === 'Texto' ? <>{range('Horizontal', 'textX', 4, 18)}{range('Vertical', 'textY', 45, 70)}{range('Tamaño del título', 'textSize', 35, 100)}</> : <>{range('Horizontal', 'imageX', 0, 100 - d.imageWidth)}{range('Vertical', 'imageY', 12, 55)}{range('Ancho de imagen', 'imageWidth', 40, 100)}</>}<button className="secondary" onClick={() => update({ textX: 7, textY: 62, textSize: 68, imageX: 7, imageY: 16, imageWidth: 86 })}>Restablecer posiciones</button></>}
    </Panel></div>
    <div className="export-actions"><button className="secondary" disabled={saving || !d.images.length || !d.title.trim()} onClick={async () => { setSaving(true); try { await onSave(); } finally { setSaving(false); } }}><Save size={18} />{saving ? 'Guardando…' : 'Guardar diseño'}</button><button className="primary" disabled={!ready || !d.images.length || !d.title.trim()} onClick={() => { if (preview) { downloadBlob(preview.blob, filename); notify('Descarga solicitada. Revisa las descargas de tu navegador.'); } }}><Download size={18} />Descargar PNG</button><button className="secondary" disabled={!ready || !d.images.length || !d.title.trim()} onClick={() => void share()}><Share2 size={18} />Compartir imagen</button></div>
    <div className="two-columns editor-bottom"><Panel title="El texto de tu publicación"><Field label="Mensaje para redes" multiline value={d.caption} onChange={caption => update({ caption })} maxLength={1500} /><Field label="Hashtags sugeridos" value={d.hashtags} onChange={hashtags => update({ hashtags })} maxLength={250} /><div className="actions"><button className="secondary" onClick={() => void copy()}><Copy size={17} />Copiar texto</button><button className="text-button" onClick={() => update({ caption: `${d.title}\n\n${d.body}\n${[d.price, d.validity, d.contact].filter(Boolean).join(' · ')}\n${d.cta}\n\n${d.hashtags}` })}>Actualizar desde el diseño</button></div><p className="hint">Al editar el flyer, actualiza este texto si quieres mantener ambos mensajes iguales.</p></Panel>
    <Panel title="Pide una nueva versión"><Field label="¿Qué te gustaría cambiar?" multiline value={request} onChange={setRequest} maxLength={700} placeholder="Ej. Hazlo más elegante y cambia el fondo a rojo." /><button className="secondary" disabled={!request.trim()} onClick={() => { update({ requests: [...d.requests, { id: crypto.randomUUID(), text: request.trim(), createdAt: new Date().toISOString(), status: 'pending' }] }); setRequest(''); notify('Solicitud añadida al borrador. Se aplicará cuando conectemos el generador.'); }}><Send size={17} />Guardar solicitud</button><p className="hint">La edición con IA está pendiente de conexión. Mientras tanto, puedes realizar cambios con las herramientas del editor.</p>{d.requests.length > 0 && <ul className="request-list">{d.requests.map(r => <li key={r.id}><span>{r.text}</span><small>Pendiente de conexión</small></li>)}</ul>}</Panel></div>
    <Panel title="Publicar o programar"><div className="tip">Publicación automática pendiente de conexión con tus redes. Puedes descargar y compartir ahora, o guardar una fecha deseada. Guardar una fecha no publicará el contenido.</div><div className="schedule-fields"><label className="field"><span>Red social</span><select value={channel} onChange={e => setChannel(e.target.value)}>{['Instagram', 'Facebook', 'WhatsApp'].map(c => <option key={c}>{c}</option>)}</select></label><Field label="Fecha y hora local" type="datetime-local" value={date} onChange={setDate} /><button className="secondary" disabled={!date} onClick={() => { if (!Number.isFinite(new Date(date).getTime()) || new Date(date).getTime() <= Date.now()) { notify('Elige una fecha y hora futuras.', true); return; } update({ schedule: { channel, at: date, status: 'pending_connection' } }); notify('Fecha añadida al borrador; publicación pendiente de conexión.'); }}>Guardar fecha deseada</button></div>{d.schedule && <div className="actions"><p className="hint">{d.schedule.channel} · {new Date(d.schedule.at).toLocaleString('es-PE')} · pendiente de conexión</p><button className="text-button" onClick={() => { update({ schedule: null }); setDate(''); }}>Quitar fecha</button></div>}</Panel>
  </div>;
}
