'use client';

import { useEffect, useRef, useState } from 'react';
import { ContentCopy, Download, Replay, Save, Send, Share, Undo } from '@mui/icons-material';
import { Alert, Box, Button, Chip, CircularProgress, MenuItem, Paper, Slider, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { Design, formats, Format } from '@/lib/studio';
import { downloadBlob, pngBlob, renderDesign } from '@/lib/studio-renderer';
import { Choices, Field, Panel, Photos } from './Fields';

const tabs = ['Texto', 'Imagen', 'Estilo', 'Posición'];

export function Editor({ design: d, update, onSave, notify, generatedImageUrl, generationStatus = 'idle', generationError, onBack }: { design: Design; update: (patch: Partial<Design>) => void; onSave: () => Promise<void>; notify: (message: string, error?: boolean) => void; generatedImageUrl?: string | null; generationStatus?: 'idle' | 'polling' | 'completed' | 'error'; generationError?: string | null; onBack: () => void }) {
  const [preview, setPreview] = useState<{ url: string; blob: Blob; design: Design } | null>(null);
  const [renderState, setRenderState] = useState<{ design: Design; error: string; rendering: boolean } | null>(null);
  const [retry, setRetry] = useState(0);
  const [tab, setTab] = useState('Texto');
  const [element, setElement] = useState('Texto');
  const [request, setRequest] = useState('');
  const [date, setDate] = useState(d.schedule?.at || '');
  const [channel, setChannel] = useState(d.schedule?.channel || 'Instagram');
  const [saving, setSaving] = useState(false);
  const drag = useRef<{ x: number; y: number; a: number; b: number; width: number; height: number; element: string } | null>(null);

  useEffect(() => {
    let live = true;
    let url = '';
    const timer = setTimeout(() => {
      const result = generatedImageUrl
        ? fetch(generatedImageUrl).then(response => { if (!response.ok) throw new Error('No se pudo cargar la imagen generada.'); return response.blob(); })
        : renderDesign(d).then(pngBlob);
      void result.then(blob => { if (!live) return; const previewUrl = generatedImageUrl || (url = URL.createObjectURL(blob)); setPreview({ url: previewUrl, blob, design: d }); setRenderState({ design: d, error: '', rendering: false }); }).catch(reason => { if (live) setRenderState({ design: d, error: reason instanceof Error ? reason.message : 'No se pudo generar la vista previa.', rendering: false }); });
    }, 100);
    return () => { live = false; clearTimeout(timer); if (url) URL.revokeObjectURL(url); };
  }, [d, generatedImageUrl, retry]);

  const rendering = !renderState || renderState.design !== d || renderState.rendering;
  const renderError = renderState?.design === d ? renderState.error : '';
  const ready = !!preview && preview.design === d && !rendering && !renderError;
  const filename = `${d.product.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9]+/g, '-').slice(0, 50) || 'publicacion'}-${d.format}.png`;
  const finalFilename = generatedImageUrl ? filename.replace(/\.png$/, '.jpg') : filename;

  async function share() {
    if (!ready || !preview) return;
    const file = new File([preview.blob], finalFilename, { type: preview.blob.type || 'image/png' });
    try { if (navigator.canShare?.({ files: [file] }) && navigator.share) await navigator.share({ files: [file], title: d.title, text: d.caption }); else { downloadBlob(preview.blob, filename); notify('Tu navegador no permite compartir archivos directamente. Iniciamos la descarga para que puedas adjuntarla en tu red social.'); } }
    catch (reason) { if ((reason as Error).name !== 'AbortError') notify('No se pudo compartir. Puedes descargar la imagen y enviarla manualmente.', true); }
  }
  async function copy() { try { await navigator.clipboard.writeText(d.caption || `${d.title}\n${d.body}\n${d.cta}\n${d.hashtags}`); notify('Texto copiado. Ya puedes pegarlo en tu publicación.'); } catch { notify('No se pudo copiar. Selecciona el texto del campo y cópialo manualmente.', true); } }
  const move = (a: number, b: number, target: string) => update(target === 'Texto' ? { textX: Math.max(4, Math.min(18, a)), textY: Math.max(45, Math.min(70, b)) } : { imageX: Math.max(0, Math.min(100 - d.imageWidth, a)), imageY: Math.max(12, Math.min(55, b)) });
  const range = (label: string, key: 'textX' | 'textY' | 'textSize' | 'imageX' | 'imageY' | 'imageWidth', min: number, max: number) => <Box><Stack direction="row" justifyContent="space-between"><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="body2" fontWeight={700}>{Math.round(d[key])}</Typography></Stack><Slider size="small" value={d[key]} min={min} max={max} onChange={(_, value) => { const next = Array.isArray(value) ? value[0] : value; update({ [key]: next, ...(key === 'imageWidth' ? { imageX: Math.min(d.imageX, 100 - next) } : {}) }); }} /></Box>;

  return <Box className="editor" sx={{ pb: 2 }}>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ xs: 'stretch', sm: 'flex-end' }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="overline" color="primary.dark" sx={{ fontWeight: 800, letterSpacing: '.12em' }}>EDITOR DE PUBLICACIÓN</Typography><Typography variant="h1">Edita tu diseño</Typography><Typography color="text.secondary">Ajusta el diseño y descárgalo cuando esté listo.</Typography></Box><Button variant="outlined" startIcon={<Undo />} onClick={onBack}>Volver al resumen</Button></Stack>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1.15fr .85fr' }, gap: 2 }}>
      <Paper variant="outlined" sx={{ p: { xs: 1.5, sm: 2.5 }, borderRadius: 2.25, borderColor: 'divider' }} aria-label="Vista previa del diseño"><Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ xs: 'stretch', sm: 'center' }} spacing={1.5} sx={{ mb: 2 }}><TextField select fullWidth label="Formato de salida" size="small" value={d.format} onChange={event => update({ format: event.target.value as Format })}>{Object.entries(formats).map(([id, format]) => <MenuItem value={id} key={id}>{format.label}</MenuItem>)}</TextField><Chip label={generatedImageUrl ? 'Imagen final para redes' : 'Maqueta local'} color="primary" variant="outlined" /></Stack>{generationStatus === 'polling' && <Alert severity="info" sx={{ mb: 2 }}>Generando tu imagen con IA…</Alert>}{generationError && <Alert severity="error" sx={{ mb: 2 }}>{generationError}</Alert>}
        <Box sx={{ minHeight: 320, display: 'flex', alignItems: 'center', justifyContent: 'center', p: { xs: 1, sm: 2 }, borderRadius: 2.5, bgcolor: '#F4F6FA', backgroundImage: 'radial-gradient(#D8E4F5 1px, transparent 1px)', backgroundSize: '16px 16px' }}><Box sx={{ position: 'relative', width: '100%', maxWidth: d.format === 'story' || d.format === 'whatsapp' ? 295 : 520, aspectRatio: `${formats[d.format].width}/${formats[d.format].height}`, bgcolor: 'common.white', borderRadius: 2, overflow: 'hidden', boxShadow: '0 12px 32px rgba(35,55,90,.14)' }}>{preview && <Box component="img" src={preview.url} alt={`Vista previa: ${d.title}`} draggable={false} sx={{ width: '100%', height: '100%', objectFit: 'contain', display: 'block' }} />}{tab === 'Posición' && <Box role="group" tabIndex={0} aria-label={`Mover ${element.toLowerCase()}. Arrastra o usa las flechas.`} onKeyDown={event => { const keys: Record<string, number[]> = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }; if (keys[event.key]) { event.preventDefault(); const [a, b] = keys[event.key]; move((element === 'Texto' ? d.textX : d.imageX) + a, (element === 'Texto' ? d.textY : d.imageY) + b, element); } }} onPointerDown={event => { const rect = event.currentTarget.getBoundingClientRect(); drag.current = { x: event.clientX, y: event.clientY, a: element === 'Texto' ? d.textX : d.imageX, b: element === 'Texto' ? d.textY : d.imageY, width: rect.width, height: rect.height, element }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { const current = drag.current; if (current) move(current.a + (event.clientX - current.x) / current.width * 100, current.b + (event.clientY - current.y) / current.height * 100, current.element); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }} sx={{ position: 'absolute', inset: 0, cursor: 'move' }}><Box sx={{ position: 'absolute', left: `${element === 'Texto' ? d.textX : d.imageX}%`, top: `${element === 'Texto' ? d.textY : d.imageY}%`, width: `${element === 'Texto' ? 94 - d.textX : d.imageWidth}%`, height: element === 'Texto' ? `${93 - d.textY}%` : '40%', border: '2px dashed', borderColor: 'secondary.main' }}><Chip size="small" label={element} color="secondary" sx={{ borderRadius: 1, position: 'absolute', top: -11, left: -2 }} /></Box></Box>}{!preview && !renderError && <Stack alignItems="center" justifyContent="center" sx={{ position: 'absolute', inset: 0 }}><CircularProgress size={28} /><Typography variant="caption" color="text.secondary" sx={{ mt: 1 }}>Preparando tu diseño…</Typography></Stack>}</Box></Box>
        <Stack direction="row" justifyContent="space-between" sx={{ mt: 1.5 }}><Typography variant="caption" color="text.secondary">{formats[d.format].width} × {formats[d.format].height} px · PNG</Typography><Typography variant="caption" color={renderError ? 'error.main' : 'success.main'} aria-live="polite">{rendering ? 'Actualizando…' : renderError ? 'Error de vista previa' : 'Vista previa actualizada'}</Typography></Stack>{renderError && <Alert severity="error" sx={{ mt: 1.5 }} action={<Button color="inherit" size="small" onClick={() => setRetry(value => value + 1)}>Reintentar</Button>}>{renderError}</Alert>}<Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.5 }}>La imagen descargada es exactamente esta vista previa. Cada formato adapta el espacio disponible.</Typography>
      </Paper>
      <Panel className="editor-controls"><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="fullWidth" sx={{ mb: 2, '& .MuiTab-root': { minWidth: 0, px: { xs: .5, sm: 1.5 }, fontSize: { xs: '.72rem', sm: '.875rem' }, whiteSpace: 'nowrap' } }}>{tabs.map(item => <Tab key={item} value={item} label={item} />)}</Tabs>
        {tab === 'Texto' && <Stack spacing={2}><Field label="Título" value={d.title} onChange={title => update({ title })} maxLength={80} /><Field label="Descripción del flyer" multiline value={d.body} onChange={body => update({ body })} maxLength={180} /><Field label="Llamado a la acción" value={d.cta} onChange={cta => update({ cta })} maxLength={40} /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: 2 }}><Field label="Precio o promoción" value={d.price} onChange={price => update({ price })} maxLength={45} /><Field label="Fecha o vigencia" value={d.validity} onChange={validity => update({ validity })} maxLength={60} /></Box><Field label="Contacto" value={d.contact} onChange={contact => update({ contact })} maxLength={35} /></Stack>}
        {tab === 'Imagen' && <Stack spacing={2}><Choices label="Ajuste de la foto" options={['Foto completa', 'Llenar marco']} value={d.imageFit === 'cover' ? 'Llenar marco' : 'Foto completa'} onChange={value => update({ imageFit: value === 'Llenar marco' ? 'cover' : 'contain' })} /><Typography variant="body2" color="text.secondary">Elige la foto principal. Las otras fotos quedan guardadas como referencias para el generador.</Typography><Box sx={{ display: 'flex', gap: 1, overflowX: 'auto' }}>{d.images.map((src, index) => <Box component="button" key={index} type="button" onClick={() => update({ selectedImage: index })} aria-label={`Usar foto ${index + 1}`} sx={{ p: 0, border: '3px solid', borderColor: index === d.selectedImage ? 'primary.main' : 'transparent', borderRadius: 2, overflow: 'hidden', width: 76, height: 60, flexShrink: 0, bgcolor: 'grey.100' }}><Box component="img" src={src} alt={`Foto ${index + 1}`} sx={{ width: '100%', height: '100%', objectFit: 'cover' }} /></Box>)}</Box><Photos images={d.images} onChange={images => update({ images, selectedImage: 0 })} />{!d.images.length && <Alert severity="warning">Agrega una foto para guardar o descargar.</Alert>}</Stack>}
        {tab === 'Estilo' && <Stack spacing={2}><Choices label="Estilo visual" options={['Moderno', 'Vibrante', 'Minimalista']} value={d.style} onChange={style => update({ style })} /><Choices label="Tipografía" options={['Sans', 'Serif']} value={d.font === 'sans' ? 'Sans' : 'Serif'} onChange={value => update({ font: value === 'Sans' ? 'sans' : 'serif' })} /><Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 2 }}><TextField label="Color principal" type="color" value={d.color} onChange={event => update({ color: event.target.value })} /><TextField label="Fondo" type="color" value={d.background} onChange={event => update({ background: event.target.value })} /></Box><Button variant="outlined" onClick={() => update({ color: d.brand.primary, background: d.brand.secondary })}>Usar colores de mi marca</Button></Stack>}
        {tab === 'Posición' && <Stack spacing={2}><Choices label="Elemento a mover" options={['Texto', 'Imagen']} value={element} onChange={setElement} /><Typography variant="body2" color="text.secondary">Arrastra sobre la vista previa, usa las flechas del teclado o ajusta estos controles.</Typography>{element === 'Texto' ? <>{range('Horizontal', 'textX', 4, 18)}{range('Vertical', 'textY', 45, 70)}{range('Tamaño del título', 'textSize', 35, 100)}</> : <>{range('Horizontal', 'imageX', 0, 100 - d.imageWidth)}{range('Vertical', 'imageY', 12, 55)}{range('Ancho de imagen', 'imageWidth', 40, 100)}</>}<Button variant="outlined" onClick={() => update({ textX: 7, textY: 62, textSize: 68, imageX: 7, imageY: 16, imageWidth: 86 })}>Restablecer posiciones</Button></Stack>}
      </Panel>
    </Box>
    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.25} justifyContent="center" sx={{ my: 2.5 }}><Button variant="outlined" disabled={saving || !d.images.length || !d.title.trim()} startIcon={<Save />} onClick={async () => { setSaving(true); try { await onSave(); } finally { setSaving(false); } }}>{saving ? 'Guardando…' : 'Guardar diseño'}</Button><Button variant="contained" disabled={!ready || !d.images.length || !d.title.trim()} startIcon={<Download />} onClick={() => { if (preview) { downloadBlob(preview.blob, finalFilename); notify('Descarga solicitada. Revisa las descargas de tu navegador.'); } }}>Descargar imagen final</Button><Button variant="outlined" disabled={!ready || !d.images.length || !d.title.trim()} startIcon={<Share />} onClick={() => void share()}>Compartir imagen</Button></Stack>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' }, gap: 2 }}><Panel title="El texto de tu publicación"><Stack spacing={2}><Field label="Mensaje para redes" multiline value={d.caption} onChange={caption => update({ caption })} maxLength={1500} /><Field label="Hashtags sugeridos" value={d.hashtags} onChange={hashtags => update({ hashtags })} maxLength={250} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button variant="outlined" startIcon={<ContentCopy />} onClick={() => void copy()}>Copiar texto</Button><Button variant="text" startIcon={<Replay />} onClick={() => update({ caption: `${d.title}\n\n${d.body}\n${[d.price, d.validity, d.contact].filter(Boolean).join(' · ')}\n${d.cta}\n\n${d.hashtags}` })}>Actualizar desde el diseño</Button></Stack><Typography variant="caption" color="text.secondary">Al editar el flyer, actualiza este texto si quieres mantener ambos mensajes iguales.</Typography></Stack></Panel><Panel title="Pide una nueva versión"><Stack spacing={2}><Field label="¿Qué te gustaría cambiar?" multiline value={request} onChange={setRequest} maxLength={700} placeholder="Ej. Hazlo más elegante y cambia el fondo a rojo." /><Button variant="outlined" disabled={!request.trim()} startIcon={<Send />} onClick={() => { update({ requests: [...d.requests, { id: crypto.randomUUID(), text: request.trim(), createdAt: new Date().toISOString(), status: 'pending' }] }); setRequest(''); notify('Solicitud añadida al borrador. Se aplicará cuando conectemos el generador.'); }}>Guardar solicitud</Button><Typography variant="caption" color="text.secondary">La edición con IA está pendiente de conexión. Mientras tanto, puedes realizar cambios con las herramientas del editor.</Typography>{d.requests.length > 0 && <Stack spacing={1}>{d.requests.map(item => <Box key={item.id} sx={{ p: 1.25, borderRadius: 2, bgcolor: '#EEF2FF', border: '1px solid', borderColor: 'divider' }}><Typography variant="body2">{item.text}</Typography><Typography variant="caption" color="text.secondary">Pendiente de conexión</Typography></Box>)}</Stack>}</Stack></Panel></Box>
    <Panel title="Publicar o programar"><Stack spacing={2}><Alert severity="info">Publicación automática pendiente de conexión con tus redes. Puedes descargar y compartir ahora, o guardar una fecha deseada.</Alert><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr auto' }, gap: 2, alignItems: 'start' }}><TextField select fullWidth label="Red social" value={channel} onChange={event => setChannel(event.target.value)}>{['Instagram', 'Facebook', 'WhatsApp'].map(item => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField><Field label="Fecha y hora local" type="datetime-local" value={date} onChange={setDate} /><Button variant="outlined" disabled={!date} onClick={() => { if (!Number.isFinite(new Date(date).getTime()) || new Date(date).getTime() <= Date.now()) { notify('Elige una fecha y hora futuras.', true); return; } update({ schedule: { channel, at: date, status: 'pending_connection' } }); notify('Fecha añadida al borrador; publicación pendiente de conexión.'); }}>Guardar fecha</Button></Box>{d.schedule && <Stack direction={{ xs: 'column', sm: 'row' }} alignItems={{ xs: 'stretch', sm: 'center' }} spacing={1}><Typography variant="caption" color="text.secondary" sx={{ flex: 1 }}>{d.schedule.channel} · {new Date(d.schedule.at).toLocaleString('es-PE')} · pendiente de conexión</Typography><Button size="small" color="error" onClick={() => { update({ schedule: null }); setDate(''); }}>Quitar fecha</Button></Stack>}</Stack></Panel>
  </Box>;
}
